spring:
  application:
    name: JhipsterSampleApplication
  threads:
    virtual:
      enabled: true
logging:
  level:
    com:
      mycompany:
        myapp: INFO
application:
  logging:
    logstash:
      tcp:
        shutdown_grace_period: PT1M
        enabled: false
        ring-buffer-size: 8192
        host: localhost
        port: 5000
