spring:
  application:
    name: JhipsterSampleApplication
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      database: jhipsterSampleApplication
      uri: mongodb://localhost:27017/jhipsterSampleApplication
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      url: redis://localhost:6379
      database: 0
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    password: ''
    driver-class-name: org.postgresql.Driver
    username: jhipsterSampleApplication
    url: jdbc:postgresql://localhost:5432/jhipsterSampleApplication
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        cache:
          use_second_level_cache: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  task:
    scheduling:
      thread-name-prefix: jhipsterSampleApplication-scheduling-
      pool:
        size: 2
    execution:
      pool:
        keep-alive: 10s
        queue-capacity: 100
        max-size: 16
      thread-name-prefix: jhipsterSampleApplication-task-
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  cassandra:
    schema-action: none
    local-datacenter: datacenter1
    contact-points: 127.0.0.1
    port: 9042
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-secret: web_app
            client-id: web_app
            scope: openid,profile,email
        provider:
          oidc:
            issuer-uri: http://localhost:9080/realms/jhipster
logging:
  level:
    com:
      mycompany:
        myapp: INFO
application:
  logging:
    logstash:
      tcp:
        shutdown_grace_period: PT1M
        enabled: false
        ring-buffer-size: 8192
        host: localhost
        port: 5000
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  security:
    oauth2:
      audience: account,api://default
kafka:
  producer:
    '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
    '[value.serializer]': org.apache.kafka.common.serialization.StringSerializer
  bootstrap-servers: localhost:9092
  consumer:
    '[value.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
    '[auto':
      offset.reset]: earliest
    '[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
    '[group.id]': myapp
  polling:
    timeout: 10000
pulsar:
  client:
    service-url: pulsar://localhost:6650
'#spring':
  cassandra:
    keyspace-name: yourKeyspace
mongock:
  migration-scan-package: com.mycompany.myapp
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    # Git Information
    git:
      mode: full
      enabled: true
    env:
      enabled: true
server:
  port: 8080
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
  enable-native-support: true
